Remove "Update Dependency graph" step because it didn't work
> Error: HTTP Status 403 for request POST https://api.github.com/repos/SwissOpenEM/keycloak-admin-helper-plugin/dependency-graph/snapshots