Return to old version because of test error
 ch.openem.keycloakadminhelperplugin.it.WorkflowIT
   org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:latest